version: '3.8'
services:
  api:
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    command: yarn start:dev
    environment:
      - NODE_ENV=development
    ports:
      - '4000:4000'
